spring:
  application:
    name: mcp-spring-java
  main:
    banner-mode: off
  jackson:
    serialization:
      fail-on-empty-beans: false
    deserialization:
      fail-on-unknown-properties: false
  ai:
    mcp:
      server:
        enabled: true
        name: my-dummy-users-server
        version: 0.0.1
        type: SYNC
        protocol: STREAMABLE  # Use STATELESS for simple HTTP POST/response transport, SSE for session based flow
        stdio: false
        resource-change-notification: true
        tool-change-notification: true
        prompt-change-notification: true
  web:
    resources:
      add-mappings: false
server:
  port: 8090
  address: 0.0.0.0  

logging:
  file:
    name: ./target/starter-webmvc-server.log
  level:
    org.springframework.web.client: DEBUG
    org.apache.http: DEBUG
    org.springframework.ai: TRACE
    org.springframework.ai.mcp: TRACE
    org.springframework.ai.tool: TRACE
    org.springframework.web.servlet.function.support.RouterFunctionMapping: TRACE
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE
    dev.rk.mcp: DEBUG